### ISSUE TITLE
Adicionar README.md com uma breve descrição do projeto

### ISSUE THREAD

**Issue by FannyVieira** [OpenDevUFCG/roadmap-cc#1]
Como ainda não discutimos muita coisa, pensei em adicionar apenas um readme com a intenção do projeto, para que seja mais fácil dos visitantes, entenderem o objetivo do projeto.
Pensei em colocar algo como:

> Roadmap ou "roteiro" para se tornar um cientista da computação na UFCG, a idéia é colocar gráficos, baseados em comentários de pessoas que já pagaram as disciplinas, demonstrando os caminhos que você precisa seguir, para ter um melhor aproveitamento do curso. Sabemos que com a nova grade, os pré-requisitos na sua grande maioria, foram deixados em aberto, o que causou grande confusão nas pessoas sobre a ordem que deveriam colocar as cadeiras. Esse repositório é destinado a todas as pessoas que se perguntam "Qual cadeira eu devo colocar no próximo semestre sem ser prejudicado por não ter pago uma anterior?"

O que vocês acham?

**Comment by FannyVieira** [comment]
Link referência: https://github.com/kamranahmedse/developer-roadmap

**Comment by juliobguedes** [comment]
Done?

**Comment by FannyVieira** [comment]
Done, vou fechar kikikiki
