### ISSUE TITLE
Quebrar coluna de areas em tabela de disciplinas

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#100]
É necessário adicionar um novo arquivo (iniciamente uma cópia de [disciplinas-ppc-2017](https://github.com/OpenDevUFCG/roadmap-cc/blob/development/data/disciplinas-ppc-2017.csv)) na pasta `data` (coloque como nome "new_disciplinas-ppc-2017.csv") que tenha a coluna `areas` em colunas respectivas aos seus valores. Por exemplo, em vez de ter a coluna `areas` teremos as colunas `Infraestrutura` ou `Dev`, pois são valores encontrados na coluna `areas`. O valor correspondente a cada coluna será 5 (se na coluna original o valor da área é a coluna da nova tabela) ou 0 (caso contrário). Exemplo:
**tabela original**

areas  | ...
--------- | ------
Infraestrutura     | ...
Dev    | ...
Dev    | ...
Infraestrutura  | ...

**nova tabela**

Infraestrutura  | Dev | ...
--------- | ------ | ------
5 | 0   | ...
0  | 5  | ...
0  | 5  | ...
5 | 0   | ...

**Comment by alexsantee** [comment]
Olá Juan! Estou olhando esse problema e gostaria de saber como tratar a área "geral". No arquivo, os campos que aparecem são geral, inteligência, dev e infra.

Parece claro que os três últimos podem ser separados, mas não sei se o campo "geral" deve ser visto como um campo prório ou como uma combinação de campos, como inteligencia=3, infra=3, dev=3.

**Comment by JuanBarros2** [comment]
Faz sentido @alexsantee ! Acho que poderíamos desconsiderar essa coluna de "geral" sem problemas.

**Comment by alexsantee** [comment]
Tudo certo! Mandei o pull request.
