### ISSUE TITLE
Implementação do vegalite na homepage

### ISSUE THREAD

**Issue by emys-alb** [OpenDevUFCG/roadmap-cc#133]
**Motivação**

- O roadmap trás a ideia de demonstrar possíveis caminhos dentro do nosso curso usando a metodologia de grafos, simulando um caminho real a ser percorrido. A nossa última versão de UX implementa um grafo interativo na home page para que o usuário já tenha ideia de como a aplicação funciona. 

**Informações importantes**

- O gráfico foi desenvolvido na biblioteca [Vega Lite](https://vega.github.io/vega-lite/) e é exportada como um JSON, você pode visualizar o gráfico [aqui](https://github.com/OpenDevUFCG/roadmap-cc/tree/v2-testes/src/Components/Home/vis-home.js).
- O componente a ser importado esse gráfico deverá ser o [Home.js](https://github.com/OpenDevUFCG/roadmap-cc/tree/v2-testes/src/Components/Home/index.jsx)
- Caso queira visualizar como o gráfico é, basta apenas jogar o arquivo (sem as importações para React) no visualizador do próprio vega, clicando [aqui](https://vega.github.io/editor)

**Comment by lucas-yago** [comment]
Boa tarde!, tenho dúvidas sobre a implementação do grafo interativo com vega. Observei que as branchs estão usando libs diferentes sendo vueJS na development e React na v2-teste, onde devo fazer a implementação? e, devo apenas implementar o grafo interativo com vega ou também devo alterar a estilização?.
Obs: nao realizei nenhuma alteração em ccs ainda pois não tenho ideia de como seja a UI ,por esse motivo ainda nao submeti um pull request.

**Comment by emys-alb** [comment]
> Boa tarde!, tenho dúvidas sobre a implementação do grafo interativo com vega. Observei que as branchs estão usando libs diferentes sendo vueJS na development e React na v2-teste, onde devo fazer a implementação? 

Boa tarde @Lucas-yago :smile: Estamos no processo de refazer o roadmap e por isso as branchs tem tecnologias diferentes, utilizamos a v2-teste para a implementação da nova versão (ou seja é v2-testes mesmo kk).

> e, devo apenas implementar o grafo interativo com vega ou também devo alterar a estilização?. 

Apenas a implementação, o grafo já segue o [design](https://www.figma.com/file/qsQWJiCbDzyZibF8Z3DnVw/Teste-Roadmap?node-id=0%3A1) que planejamos para a nova versão.

> Obs: nao realizei nenhuma alteração em ccs ainda pois não tenho ideia de como seja a UI ,por esse motivo ainda nao submeti um pull request.

Tranquilo e fico muuuuito feliz com a sua contribuição :heart:
