### ISSUE TITLE
Adicionar mapas por especialidades

### ISSUE THREAD

**Issue by thiagomanel** [OpenDevUFCG/roadmap-cc#15]
Oi pessoal, não tenho certeza se está no escopo do projeto mas acho que seria útil ter um mapa que considerasse as optativas dividido por especialidades. Por exemplo, que optativas um aluno que gosta de eng. sw deveria se escolher se especializar no tema (e também para "programador de sistemas", analista de dados etc)

p.s Massa a iniciativa!

**Comment by JuanBarros2** [comment]
Oi @thiagomanel! Muito obrigado pela contribuição! Estamos sim com esse foco. Já entramos em contato com o analytics para conseguir atualizar as informações que estão disponível no site do cursos ufcg. Após a semana do fera começaremos a trabalhar numa versão interativa (com D3) com informações para auxiliar a criar essas áreas de interesse. O problema atual é definir as possíveis áreas que exibiremos nessa versão inicial, tendo em vista que é necessário conversar com várias pessoas que já pagaram as disciplinas para saber as suas opiniões sobre essas cadeiras e a relação com as cadeiras que criam dependência.
