### ISSUE TITLE
Tradução usando libs (i18n)

### ISSUE THREAD

**Issue by franklingg** [OpenDevUFCG/roadmap-cc#175]
**Sua requisição de feature é relacionada a um problema? Por favor descreva.**
Atualmente existe um pequeno esforço para traduções no sistema (no arquivo `src/components/Pt-Br.js`), mas essa solução foge do padrão e não é escalável.

**Descreva a solução que você gostaria**
Usar uma biblioteca consolidada de internacionalização (como o [i18n](https://www.npmjs.com/package/i18n)) para tornar a tradução automática e simples

**Contexto adicional**
Um guia muito bom para adicionar a [internacionalização no Next](https://medium.com/@lucas_pinheiro/como-adicionar-internacionalização-i18n-na-sua-aplicação-react-a1ac4aea109d).

**Comment by franklingg** [comment]
Não é prioritário no momento

**Comment by LeandraOS** [comment]
Eu acho uma ótima feature! 
Pode ser uma task feita quando o projeto já estiver com um andamento mais avançado.
Mas na minha opinião, vem aí!!!
