### ISSUE TITLE
Adicionar Storybook ao projeto

### ISSUE THREAD

**Issue by NicolasLopes7** [OpenDevUFCG/roadmap-cc#195]
Essa issue tem como objetivo implementar o [Storybook](https://storybook.js.org/) no projeto.

## O que é o Storybook?
Storybook é uma ferramenta que tem como objetivo servir de ambiente isolado para você criar seus componentes. Ou seja, você não precisa desenvolver seu componente diretamente no seu sistema.

A ideia dos componentes é que eles precisam ser reutilizáveis. Se você cria diretamente no seu sistema, algum JS ou CSS do sistema pode influenciá-lo. Além disso, você pode cair na tentação de integrar o componente com alguma fonte de dados para facilitar o acesso a algum dado. E isso já acaba com a possibilidade de reutilização.

Além disso, o componente corre o risco de ficar mais complexo, dificultando na hora de testá-lo.

## Como o Storybook irá nos ajudar?
- Com o storybook você poderá adicionar os componentes a uma `História` e nele colocar descrições das props necessárias (bem útil já que não estamos usando typescript).
- Desenvolver os componentes independentemente de páginas estarem prontas ou não
- Criar todas as possíveis variações dele (alterando as props)
- Testar diferentes tamanhos de tela

**Comment by NicolasLopes7** [comment]
Pode dar assignee p mim @LeandraOS ?

**Comment by LeandraOS** [comment]
> Pode dar assignee p mim @LeandraOS ?

Feito!
