### ISSUE TITLE
Definir qual métrica usaremos para estabelecer os pré-requisitos das disciplinas

### ISSUE THREAD

**Issue by FannyVieira** [OpenDevUFCG/roadmap-cc#2]
Usaremos apenas a opinião da maioria das pessoas, para definir os pré-requisitos de uma disciplina? Buscamos informarções também com os professores acessíveis que costumam dar essas disciplinas? Há algum lugar que possamos obter essas informações?

Estava pensando em criar uma issue para cada disciplina, porque acho que vai ficar uma bagunça se discutirmos isso apenas nessa thread.

O que acham?

**Comment by JuanBarros2** [comment]
Acho muito válido @FannyVieira . Uma boa conversar com os graduados e ver a opinião deles, quais assuntos se relacionam e a importância deles. Mas acho válido também analisar antes, pois a grade nova veio com várias mudanças e é bom identificar elas.

**Comment by JuanBarros2** [comment]
Penso já em algumas frentes que tem destaque para os estudantes: Ciência de Dados, Web Dev e Programação Competitiva. Vocês conseguem ver outras? Eu sei que tem optativas para a área de redes e conectividade, banco de dados e empreendedorismo, mas acho que precisamos conversar com pessoas que já pagaram as cadeiras.

**Comment by FannyVieira** [comment]
Acho que podia juntar essas em DevOps

**Comment by FannyVieira** [comment]
> Acho muito válido @FannyVieira . Uma boa conversar com os graduados e ver a opinião deles, quais assuntos se relacionam e a importância deles. Mas acho válido também analisar antes, pois a grade nova veio com várias mudanças e é bom identificar elas.

Concordo, acho que a gente podia fazer um esboço inicial e ir validando e incrementando com a opinião das outras pessoas
