### ISSUE TITLE
Adicionar versionamento no README

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#28]
A atual README está muito básica e pouco informativa.
Acho que seria uma boa documentar melhor sobre como estamos versionando o repositório.
Adicionar uma sessão de versionamento resolveria esse problema. Encontrei o seguinte 
exemplo que mostra como outro projeto resolveu o problema: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

Acho que [esse](https://semver.org/lang/pt-BR/) versionamento casa com o nosso.

**Comment by FannyVieira** [comment]
No caso a gente criaria umas tags que é1 como se fosse uma branch pras versões do repositório?

**Comment by JuanBarros2** [comment]
Isso, o sistema de tag'amento do git permite isso

**Comment by FannyVieira** [comment]
Beleza

**Comment by FannyVieira** [comment]
Gostei muito desse sistema, pisou na sugestão
