### ISSUE TITLE
Adicionar política de branchs do repositório

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#29]
É necessário especificar no [guia de contribuição](https://github.com/OpenDevUFCG/roadmap-cc/blob/master/CONTRIBUTING.md) que utilizaremos a master apenas para versões "MAIOR" do roadmap, ou seja, apenas versões que tiverem grandes alterações ao ponto de mudar a API do projeto.

**Comment by FannyVieira** [comment]
Tem a master a dev e a gente cria a partir da dev, certo?

**Comment by JuanBarros2** [comment]
Isso
