### ISSUE TITLE
Esboço e design do roadmap

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#4]
Precisamos de uma versão inicial estática para mostrar as dependências das principais cadeiras da graduação. Seria legal que cada um criasse esboços de mapas para dispor as imagens.

**Comment by JuanBarros2** [comment]
@FannyVieira acho que essa tarefa poderia ser facilitada com ajuda de pessoas que pagaram visualização da informação. O que você acha?

**Comment by JuanBarros2** [comment]
Inicialmente precisamos dispor as seguintes informações: Cadeiras, Níveis de dependências entre elas, quantidade de vagas ofertadas por cadeiras e área que pode ser classificada (opcional).

**Comment by FannyVieira** [comment]
> @FannyVieira acho que essa tarefa poderia ser facilitada com ajuda de pessoas que pagaram visualização da informação. O que você acha?

Concordo, eles tem mais ideia de como ajudar as pessoas a compreender melhor os dados.

**Comment by FannyVieira** [comment]
> Encontrei esse modelo que é muito utilizado aqui no github e acho que talvez seja uma boa começar por ele. O que acham? https://github.com/togiberlin/ui-ux-designer-roadmap

Muito bommm, tava pensando em inicialmente ser algo bem estático, com essa visualização, depois a gente vai deixando interativo

**Comment by FannyVieira** [comment]
> Inicialmente precisamos dispor as seguintes informações: Cadeiras, Níveis de dependências entre elas, quantidade de vagas ofertadas por cadeiras e área que pode ser classificada (opcional).

Sim, estou tentando ver onde podemos obter essas informações, por enquanto, achei informações sobre as cadeiras [aqui](https://docs.google.com/spreadsheets/d/1ZDAFBaHfyo3frFHQCM2YB2vYTeN4R__QJkuO4a9xwrM/edit#gid=403042829) e sobre as dependencias [aqui](https://drive.google.com/file/d/0B_94ash-JfI8OEJIX3hfdFFFNkU/view) por volta da página 27, só que a gente teria que transcrever isso

**Comment by FannyVieira** [comment]
Sobre a quantidade de vagas eu sei que isso fica no controle acadêmico, só que ela só é disponibilizada durante a matrícula e durante o ano letivo, agora por exemlo, a parte de turmas ofertadas não tem nada

**Comment by FannyVieira** [comment]
E a área que ela pode ser classificada vai ter que ser pela opinião do povão msm

**Comment by JuanBarros2** [comment]
@FannyVieira falei com @joseims e ele falou que podia ajudar a gente também.

**Comment by FannyVieira** [comment]
> @FannyVieira falei com @joseims e ele falou que podia ajudar a gente também.

Show!

**Comment by FannyVieira** [comment]
> > > Inicialmente precisamos dispor as seguintes informações: Cadeiras, Níveis de dependências entre elas, quantidade de vagas ofertadas por cadeiras e área que pode ser classificada (opcional).
> > 
> > 
> > Sim, estou tentando ver onde podemos obter essas informações, por enquanto, achei informações sobre as cadeiras [aqui](https://docs.google.com/spreadsheets/d/1ZDAFBaHfyo3frFHQCM2YB2vYTeN4R__QJkuO4a9xwrM/edit#gid=403042829) e sobre as dependencias [aqui](https://drive.google.com/file/d/0B_94ash-JfI8OEJIX3hfdFFFNkU/view) por volta da página 27, só que a gente teria que transcrever isso
> 
> Mas se a gente pode fazer uma versão mais clean logo pra ter algo até o fim de fevereiro e depois buscar as informações complementares depois.

Sim, beleza, depois eu subo as infos das optativas e a gente discute as areas de cada cadeira e os pré-requisitos pq tem uns que tão estranhos seria bom a gente discutur

**Comment by JuanBarros2** [comment]
![image](https://user-images.githubusercontent.com/11728655/52181579-22aeb080-27d2-11e9-9d5b-9751d34ed6be.png)

**Comment by JuanBarros2** [comment]
Essa ferramenta é colaborativa também e podemos gerar um JSON que pode ser utilizado por outras pessoas também

**Comment by FannyVieira** [comment]
> Essa ferramenta é colaborativa também e podemos gerar um JSON que pode ser utilizado por outras pessoas também

Sim, muito bom
