### ISSUE TITLE
Adicionar arquivo de CHANGELOG.md

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#41]
**Sua requisição de feature é relacionada a um problema? Por favor descreva.**
Uma boa prática da comunidade open source é manter as versões da aplicação 
bem documentada para que tenha um histórico claro das melhorias e correções
que são feitas no repositório. Além disso, é possível traquear as mudanças que
ocorrerão de uma versão para outra. O roadmap-cc versiona o repositório, mas
não tem nenhum arquivo que descreva isso de forma clara para os contribuintes.

**Descreva a solução que você gostaria**
Adicionar um arquivo MD de CHANGELOG para traquear as versões do roadmap.

**Descreva alternativas que você considerou**
Encontrei [um guia básico de regras](https://keepachangelog.com/pt-BR/0.3.0/) que podem ser adotadas em repositórios. Ele
fala que as informações contidas nele são 

> minha cuidadosa opinião, junto com as informações e exemplos que reuni.

mas acho que podemos utilizar boa parte dessas regras no repositório.

**Contexto adicional**
Na aba de release já temos uma versão automatizada do CHANGELOG, mas seria
legal ir adicionando no novo arquivo e só criar a versão do release quando a versão
for finalizada e estiver pronta para produção.

**Comment by FannyVieira** [comment]
Bacana , eu tava olhando os repositórios da vtex, e vi que eles [tinham](https://github.com/vtex-apps/store-components/blob/master/CHANGELOG.md), ia até comentar aqui. Muito bom, estou de acordo
