### ISSUE TITLE
Discussão sobre áreas principais a serem adicionadas

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#46]
**Sua requisição de feature é relacionada a um problema? Por favor descreva.**

Ainda não temos definidas as principais áreas que classificarão as disciplinas. No nosso
csv que contém as informações sobre as [disciplinas](https://github.com/OpenDevUFCG/roadmap-cc/blob/development/data/disciplinas-ppc-2017.csv), temos a coluna "area", mas precisamos
definir quais áreas iremos adicionar para gerar um conjunto pré definido delas. Seria necessário
abrir a discussão para pessoas que já tiveram pago optativas para entender quais as áreas
que podemos começar a classificar e documentar o repositório para aceitar sugestões de
alteração dos nossos dados sobre disciplinas.

**Descreva a solução que você gostaria**
Essa issue é responsável por abrir a discussão sobre quais as melhores áreas para classificar
as disciplinas e é esperado a participação aberta da comunidade.

**Descreva alternativas que você considerou**
As opções iniciais que pensei foi "devops", "data science" e "web develop".

**Comment by JuanBarros2** [comment]
Já recebemos algumas indicações em #15

**Comment by FannyVieira** [comment]
Já vi algumas pessoas sugerindo "Programação Competitiva", que envolve algumas cadeiras de matemática, ATAL, AA, P1 dá um pontapé inicial muito grande

**Comment by thayannevls** [comment]
Com certeza alguma área de *Data Science* que prioriza você pagar probabilidade e estatística o mais rápido possível para ser possível pagar cadeiras optativas que são focadas em análise e visualização de dados

**Comment by thayannevls** [comment]
@raylamedeiros Talvez tu se interesse por essa issue

**Comment by RaylaMedeiros** [comment]
Poderia ter também uma área de testes, sei que há algumas optativas relacionadas a isso

**Comment by JuanBarros2** [comment]
Conversando com Nazareno ele me indicou algumas "trilhas" que foram pensadas para serem ofertadas em todo período. A ideia é que todo semestre tenha uma quantidade mínima de cadeiras de cada trilha para que os alunos possam escolher alguma área que eles mais se interessarem. As trilhas são **Dev, Infraestrutura e Inteligência.**

**Comment by fanny** [comment]
Sendo assim, acho que a discussāo agora, seriam quais cadeiras podem ser mapeadas pra cada trilha dessa, certo?

**Comment by JuanBarros2** [comment]
Eu tenho uma lista com as optativas e as trilhas que eles pensaram ser de qual trilha. Achei bem válido a classificação deles. Poderíamos agora automatizar a classificação com base nas dependências das cadeiras obrigatórias. Exemplo: Visualização está na trilha inteligencia, então Probabilidade, que é pre requisito de Visualização será da trilha Inteligencia também.

**Comment by fanny** [comment]
De fato, acho muito valido tb

**Comment by JuanBarros2** [comment]
Para finalizar a issue: Foi acertado em seguir as três áreas "Inteligencia, Dev e Infraestrutura"

**Comment by JuanBarros2** [comment]
Andei avaliando a possibilidade de não existir apenas uma classificação de cada área, mas sim níveis de pertencimento de uma disciplina em dada área. 
Por exemplo: Teoria Dos Grafos, 
Matemática: 4/5
Desenvolvimento: 3/5
Infraestrutura: 0/5.
O que vocês acham dessa abordagem? Seria preciso de mais dados
