### ISSUE TITLE
Adicionar dados de relação em laguinho

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#52]
**Sua requisição de feature é relacionada a um problema? Por favor descreva.**
Não temos os dados das [dependências](https://github.com/OpenDevUFCG/roadmap-cc/blob/development/data/relacionamentos-disciplinas-ppc2017.csv) no laguinho para fazer a requisição.

**Descreva a solução que você gostaria**
Adicionar o endpoint de dependência no laguinho para que assim
seja possível realizar a chamada para lá.

**Comment by fanny** [comment]
Feito em [#25](https://github.com/OpenDevUFCG/laguinho-api/pull/25)
