### ISSUE TITLE
Adicionar siglas das disciplinas e link para Tamburetei

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#54]
**Sua requisição de feature é relacionada a um problema? Por favor descreva.**
Os dados disponíveis das [disciplinas](https://github.com/OpenDevUFCG/roadmap-cc/blob/development/data/disciplinas-ppc-2017.csv) possuem as colunas `sigla`
e `dicas` cujo objetivo é mapear os links do [Tamburetei](https://github.com/OpenDevUFCG/Tamburetei) dessas disciplinas, mas essas informações estão incompletas.

**Descreva a solução que você gostaria**
Adicionar os valores corretos das linhas faltantes, caso exista.

**Descreva alternativas que você considerou**
Realizar a alteração no CSV e submeter o pull request no repositório.

**Contexto adicional**
Disciplinas Faltantes
- [x] Introdução à Probabilidade		
- [x] Projeto de Software		
- [x] Paradigmas de Linguagens de Programação	Obrigatório	
- [x] Banco de dados I			
- [x] Organização e Arquitetura de Computadores
- [x] Laboratório de Organização e Arquitetura de Computadores
- [x] Estatística Aplicada			
- [x] Análise de Sistemas			
- [x] Engenharia de Software			
- [x] Redes de Computadores		
- [x] Sistemas Operacionais			
- [x] Teoria da Computação			
- [x] Metodologia Científica		
- [x] Programação Concorrente			
- [x] Inteligência Artificial		
- [x] Análise e Técnicas de Algoritmos			
- [ ] Compiladores		
- [ ] Projeto em Computação I			
- [ ] Projeto de Trabalho de Conclusão de Curso	
- [ ] Projeto em Computação II		
- [ ] Trabalho de Conclusão de Curso			
- [ ] Administração de Sistemas		
- [ ] Administração de Sistemas Gerenciadores de Bancos de Dados	
- [x] Algoritmos Avançados I		
- [ ] Algoritmos Avançados II		
- [ ] Algoritmos Avançados III		
- [ ] Algoritmos Avançados IV		
- [ ] Arquitetura de Software			
- [ ] Avaliação de Desempenho de Sistemas Discretos	
- [ ] Banco de Dados II			
- [ ] Computação Gráfica			
- [ ] Computação e Música			
- [ ] Desenvolvimento de Aplicações Corporativas Avançadas	
- [ ] 	Desenvolvimento de Software Integrado à Infraestrutura			
- [ ] 	Economia de Tecnologia da Informação			
- [ ] 	Empreendedorismo em Software		
- [ ] 	Gerência de Redes		
- [ ] 	Interconexão de Redes de Computadores			
- [ ] Interface Homem- Máquina		
- [ ] Otimização			
- [ ] Métodos e Software Numéricos	
- [ ] Métodos Formais		
- [ ] Prática de Ensino em Computação I		
- [ ] Prática de Ensino em Computação II		
- [ ] Princípios de Desenvolvimento Web		
- [ ] Programação em Banco de Dados	
- [ ] Projeto de Redes de Computadores
- [ ] Provisionamento e Operação de Infraestrutura
- [ ] Reconhecimento de Padrões e Redes Neurais
- [ ] Recuperação da Informação e Busca na Web			
- [ ] Segurança de Sistemas		
- [ ] Sistemas de Apoio à Decisão
- [ ] Sistemas de Informação Geográfica		
- [x] Sistemas Distribuídos
- [ ] Verificação e Validação de Software			
- [ ] Visão Computacional	
- [ ] TECC(PROJETO DE SISTEMAS OPERACIONAIS)				
- [ ] TECC(GESTAO DE PROJETOS)
- [ ] TECC(CIENCIA DE DADOS DESCRITIVA)		
- [ ] TECC(PERCEPCAO COMPUTACIONAL	
- [ ] Administração e Empreendedorismo	
- [ ] Álgebra Vetorial e Geometria Analítica	
- [ ] Cálculo Diferencial e Integral III		
- [ ] Direito e Cidadania		
- [ ] Economia	Optativa Geral	4		
- [ ] Física Geral I	
- [ ] Física Geral II	
- [ ] Física Geral III		
- [ ] Física Geral IV			
- [ ] Informática e Sociedade		
- [ ] Inglês
- [ ] Libras – Língua Brasileira de Sinais		
- [ ] Língua Portuguesa				
- [ ] TECC(JOGOS DIGITAIS)	TECC(PROGRAMACAO FUNCIONAL)		
- [ ] TECC(CIÊNCIA DE DADOS PREDITIVA)	
- [ ] TECC(VISUALIZAÇÃO DE DADOS)

**Comment by RicardoAndradeM** [comment]
Vou adicionar os links disponíveis restantes, e as siglas que eu conseguir.
