### ISSUE TITLE
Necessidade de estruturação dos dados coletados pessoalmente

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#6]
@OpenDevUFCG/roadmap tava pensando em como podemos gerar os valores das dificuldades. Estamos entrevistando estudantes mas não estamos estruturando esse dado para pesquisa fultura. Vocês acham válido perguntar se podemos registrar as respostas em um CSV sem identificação da pessoa aqui no repositório? Acho válido ter esses dados abertos também, mas não sei até que ponto as pessoas ficariam confortáveis.

**Comment by FannyVieira** [comment]
Aho que nem todo mundo vai se sentir confortável em ter o nome divulgado, acho que é interessante sim deixar aberto as respostas, caso alguem também queira fazer alguma manipulação, por exemplo, mas sem revelar a identidade das pessoas, já que é algo de certa forma subjetivo

**Comment by thayannevls** [comment]
O Tamburetei também vai precisar. Talvez invés de CSV na tora, usar o google formulário? Ele coloca as respostas em um CSV, faz o gráficos e tudo mais. Ficaria mais simples.

**Comment by JuanBarros2** [comment]
Boa Ideia @thayannevls ! Tem alguem do @OpenDevUFCG/tamburetei que possa se juntar para fazermos esse form?

**Comment by FannyVieira** [comment]
Seria bom definir as informações que queremos coletar no form, a gente precisa da dificuldade, mas colocamos em que escala 1-5? E como o pessoal do  @OpenDevUFCG/tamburete precisa, seria bom saber de que eles precisa pra jja incluir

**Comment by FannyVieira** [comment]
Porque fazer o form é rapidinho
