### ISSUE TITLE
Dados que precisaremos na primeira versão

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#7]
@OpenDevUFCG/roadmap o que vocês acham de documentar essa parte de como estamos adquirindo os dados na wiki do repositório?

**Comment by FannyVieira** [comment]
Acho válido sim, principalmente porque ta sendo manual, eu tinha pensado em colocar os arquivos de onde extrai e porque vai levar em consideração a opiniao das pessoas
