### ISSUE TITLE
Adicionar tópico sobre aquisição de dados em geral

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#8]
É necessário adicionar um tópico na Wiki explicando qual nossa política sobre os dados a serem colocados no repositório.

**Comment by JuanBarros2** [comment]
@FannyVieira encontrei as principais rotas utilizadas pelo analytics para retornar os dados. As endpoints estão hospedadas em http://analytics.ufcg.edu.br/pre/ciencia_da_computacao_i_cg/ e entrarei em contato com os mainteiners do bd para atualizarem os dados. Segue imagem das rotas disponíveis da API
![image](https://user-images.githubusercontent.com/11728655/53668376-8782ec80-3c52-11e9-9aba-deab80d40080.png)

**Comment by FannyVieira** [comment]
Aqui dá 404 not found

**Comment by FannyVieira** [comment]
Mas top

**Comment by FannyVieira** [comment]
Nós vamos usar esses dados pra essa primeira versão? Como temos ~1semana tu acha que daria certo?

**Comment by JuanBarros2** [comment]
Tu colocou o segundo?

**Comment by JuanBarros2** [comment]
A gente usaria na versão programática com javascript + d3 depois da SdF

**Comment by FannyVieira** [comment]
> Tu colocou o segundo?

Como assim o segundo? Tentei abrir esse link, deu erro

**Comment by JuanBarros2** [comment]
eu mandei o print das rotas que existem, vc testou colocar alguma delas no final?

**Comment by FannyVieira** [comment]
Ahh entendi, funcionou sim
