### ISSUE TITLE
Adicionar icone de aplicação

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#94]
Atualmente o logo da aplicação não esta sendo mostrada na aba do navegador corretamente. A imagem padrão é a que vem ao construir um projeto Vue. É preciso modificar para a logo atual do roadmap-cc. É preciso ter cuidado com as dimensões do ícone pois geralmente eles tem baixa resolução. Por isso, seria legal testar se fica direitinho no browser quando alterado. :smile:

**Comment by JorgeAndd** [comment]
Vou tentar fazer 👍
