### ISSUE TITLE
Ícone não está sendo renderizado em Chrome

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#96]
Em #95 foi feita a atualização do favicon para a logo do projeto.

Contudo, a logo não está sendo renderizada em alguns computadores
com Chrome. Ao abrir no firefox a imagem aparece perfeitamente. Precisa
ser feito uma investigação do que pode estar gerando o problema (talvez a 
versão do chrome? Sistema Operacional?). Adianto que o problema não é
de cache, pois limpei todo o cache da máquina e tentei abrir em modo anonimo
e o problema persistiu.

**Comment by lnalmeida** [comment]
Tenho o mesmo problema. batalhando pra descobrir as causas.

**Comment by JuanBarros2** [comment]
@lnalmeida Agradeço se comentar por aqui se descobrir a causa :D
