### ISSUE TITLE
Trocar trilha "Inteligencia" por "Matemática

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/roadmap-cc#99]
A tabela de [disciplinas](https://github.com/OpenDevUFCG/roadmap-cc/blob/development/data/disciplinas-ppc-2017.csv) tem a coluna "area" e dentre os valores possíveis está o valor "Inteligência". Contudo, para futuras alterações do roadmap-cc, é preciso
mudar seu nome para "Matemática" para que faça mais sentido. A tarefa é renomear os campos
onde aparece "Inteligencia" e substitui-lo por "Matemática".

**Comment by JuanBarros2** [comment]
**[UPDATE]** - O arquivo de disciplina está sendo atualizado para outro arquivo que será utilizado em seu lugar (Vide #100) . Agora ele tem 3 colunas que representam as áreas das trilhas que existe atualmente no roadmap-cc. O arquivo se encontra em `/data/new_disciplinas-ppc-2017.csv` e precisa ser atualizada a coluna com o nome novo. 
Para isso, seria necessário apenas substituir o nome da coluna e o problema seria resolvido para todos os valores. Não é mais necessário atualizar o arquivo anterior visto que ele não será mais utilizado.

**Comment by lucasmfb** [comment]
Feito em #103
